### ISSUE TITLE
Better error message for pierone

### ISSUE THREAD

**Issue by sina-golesorkhi** [zalando-stups/pierone#75] opened 2016-04-22 15:33 UTC
Hi there. 

On pushing the docker image to pierone if you are not logged in to the pierone you will get the following error message: 
`<nil>
`
which is not much helpful specially for those who are new to STUPS. 
It would be nice to remind the user that he/she probably has forgotten to login to pierone just the way that Git works which provides you with a possible solution in every error message. 

Thanks.

**Comment by hjacobs** [comment] 2016-04-22 15:36
@sina-golesorkhi this is a duplicate of #60 -- the Docker client is pretty stupid as it expects a proprietary error JSON response and it only spits out the "nil" if a 401 status code is returned (it _could_ show at least the status code :disappointed: )

**Closed as completed by hjacobs** 2016-04-22 15:36 UTC

**Comment by sina-golesorkhi** [comment] 2016-04-22 15:44
@hjacobs hmm thank you for referring to the #60. It is such a pity that you should deal with that JSON.
